import { zodResolver } from '@hookform/resolvers/zod'
import { useEffect, useMemo, useState } from 'react'
import { useFieldArray, useForm } from 'react-hook-form'
import { useNavigate, useParams } from 'react-router-dom'
import { z } from 'zod'
import { createScenario, fetchScenarioById, updateScenario } from '../features/scenario/api/scenarioRepository'
import { SCENARIO_STATUS_OPTIONS, type ScenarioFormValues } from '../features/scenario/model/types'
import { hasSupabaseEnv, supabaseEnvErrorMessage } from '../infra/supabase/client'

const defaults = ['Rent', 'Fixed salary', 'Depreciation', 'Software subscription', 'Other fixed cost']
const fixedItemSchema = z.object({ name: z.string().trim().min(1), amount: z.coerce.number().finite().min(0), sortOrder: z.coerce.number().int().min(0) })
const schema = z.object({ name: z.string().trim().min(1).max(100), targetYearMonth: z.string().regex(/^\d{4}-\d{2}$/), unitPrice: z.coerce.number().finite().min(0), quantity: z.coerce.number().finite().min(0), variableCostPerUnit: z.coerce.number().finite().min(0), fixedCost: z.coerce.number().finite().min(0), fixedCostItems: z.array(fixedItemSchema), note: z.string().trim().max(2000).optional().or(z.literal('')), status: z.enum(['draft', 'final']) })
const numberParser = (value: unknown) => (typeof value === 'number' ? (Number.isFinite(value) ? value : 0) : typeof value === 'string' && value.trim() !== '' && Number.isFinite(Number(value)) ? Number(value) : 0)

export function ScenarioEditorPage() {
  const navigate = useNavigate(); const { id } = useParams<{ id: string }>(); const isEdit = Boolean(id)
  const [submitError, setSubmitError] = useState<string | null>(null); const [loading, setLoading] = useState(false)
  const defaultMonth = useMemo(() => new Date().toISOString().slice(0, 7), [])
  const { register, control, watch, setValue, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<ScenarioFormValues>({ resolver: zodResolver(schema), defaultValues: { name: '', targetYearMonth: defaultMonth, unitPrice: 0, quantity: 0, variableCostPerUnit: 0, fixedCost: 0, fixedCostItems: defaults.map((name, i) => ({ name, amount: 0, sortOrder: i })), note: '', status: 'draft' } })
  const { fields, append, remove } = useFieldArray({ control, name: 'fixedCostItems' })
  const items = watch('fixedCostItems') ?? []
  const totalFixedCost = useMemo(() => items.reduce((a, b) => a + (Number.isFinite(b.amount) ? Number(b.amount) : 0), 0), [items])
  useEffect(() => { setValue('fixedCost', totalFixedCost) }, [totalFixedCost, setValue])

  useEffect(() => { if (!id) return; void (async()=>{ setLoading(true); try { const sc = await fetchScenarioById(id); if (sc) reset({ ...sc, fixedCostItems: sc.fixedCostItems?.length ? sc.fixedCostItems.map((it)=>({name: it.name, amount: it.amount, sortOrder: it.sortOrder})) : defaults.map((name, i) => ({ name, amount: 0, sortOrder: i })) }) } finally { setLoading(false) } })() }, [id, reset])

  const onSubmit = async (values: ScenarioFormValues) => { setSubmitError(null); try { const payload = { ...values, fixedCost: totalFixedCost, fixedCostItems: values.fixedCostItems?.filter((item)=>item.name.trim().length>0).map((item, idx)=>({ ...item, sortOrder: idx })) ?? [] }; const saved = isEdit && id ? await updateScenario(id, payload) : await createScenario(payload); navigate(`/scenarios/${saved.id}`) } catch (error) { setSubmitError(`${isEdit ? 'Failed to update scenario' : 'Failed to save scenario'}: ${error instanceof Error ? error.message : 'Unknown error'}`) } }

  return <section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="text-lg font-medium">Scenario Editor</h2>{loading && <p className='mt-2 text-sm text-slate-600'>Loading scenario...</p>} {!hasSupabaseEnv && <p className="mt-3 rounded-md border border-amber-300 bg-amber-50 p-2 text-sm text-amber-800">{supabaseEnvErrorMessage}</p>}<form onSubmit={handleSubmit(onSubmit)} className="mt-5 grid gap-4">{[['name','Scenario name','text'],['targetYearMonth','Target year/month','month'],['unitPrice','Unit price','number'],['quantity','Quantity','number'],['variableCostPerUnit','Variable cost per unit','number']] .map(([field,label,type]) => <label key={field} className='grid gap-1 text-sm'><span>{label}</span><input type={type} step={type==='number'?'0.01':undefined} className='rounded-md border px-3 py-2' {...register(field as keyof ScenarioFormValues, type==='number'?{setValueAs:numberParser}:undefined)} />{errors[field as keyof ScenarioFormValues] && <span className='text-xs text-rose-600'>{String(errors[field as keyof ScenarioFormValues]?.message ?? '')}</span>}</label>)}
    <div className='rounded-lg border p-4'><h3 className='text-sm font-medium'>Fixed Cost Breakdown</h3><div className='mt-3 grid gap-2'>{fields.map((field, idx)=><div key={field.id} className='grid grid-cols-[1fr_180px_auto] gap-2'><input className='rounded-md border px-3 py-2 text-sm' placeholder='Name' {...register(`fixedCostItems.${idx}.name`)} /><input type='number' step='0.01' className='rounded-md border px-3 py-2 text-sm' {...register(`fixedCostItems.${idx}.amount`, { setValueAs: numberParser })} /><button type='button' className='rounded-md border px-3 py-2 text-xs' onClick={()=>remove(idx)}>Delete</button></div>)}</div><button type='button' className='mt-3 rounded-md border px-3 py-2 text-sm' onClick={()=>append({ name: '', amount: 0, sortOrder: fields.length })}>Add fixed cost item</button><div className='mt-3 rounded-md bg-slate-50 px-3 py-2 text-sm'><span className='font-medium'>Total Fixed Cost: </span>{new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(totalFixedCost)}</div></div>
    <label className='grid gap-1 text-sm'><span>Fixed cost (read-only total)</span><input type='number' readOnly className='rounded-md border bg-slate-50 px-3 py-2' value={totalFixedCost} /></label>
    <label className='grid gap-1 text-sm'><span>Note</span><textarea rows={4} className='rounded-md border px-3 py-2' {...register('note')} /></label><label className='grid gap-1 text-sm'><span>Status</span><select className='rounded-md border px-3 py-2' {...register('status')}>{SCENARIO_STATUS_OPTIONS.map((status)=><option key={status} value={status}>{status}</option>)}</select></label>{submitError && <p className='rounded-md bg-rose-50 p-2 text-sm text-rose-700'>{submitError}</p>}<button type='submit' disabled={isSubmitting} className='rounded-md bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-60'>{isSubmitting ? (isEdit ? 'Updating...' : 'Saving...') : (isEdit ? 'Update scenario' : 'Save scenario')}</button></form></section>
}
