import { getSupabaseClient } from '../../../infra/supabase/client'
import type { AnalysisDimension, AnalysisDimensionValue } from '../model/types'
const req = async()=>{const {data,error}=await getSupabaseClient().auth.getUser(); if(error||!data.user) throw new Error(error?.message??'Authentication required'); return data.user.id}
const mapD=(r:any):AnalysisDimension=>({id:r.id,ownerUserId:r.owner_user_id,key:r.key,name:r.name,sortOrder:r.sort_order})
const mapV=(r:any):AnalysisDimensionValue=>({id:r.id,ownerUserId:r.owner_user_id,analysisDimensionId:r.analysis_dimension_id,code:r.code,name:r.name,sortOrder:r.sort_order})
export async function listDimensions(){const u=await req(); const {data,error}=await getSupabaseClient().from('analysis_dimensions').select('*').eq('owner_user_id',u).order('sort_order').order('name'); if(error) throw new Error(`Failed to load analysis dimensions: ${error.message}`); return (data??[]).map(mapD)}
export async function createDimension(input:{key:string;name:string}){const u=await req(); const {data,error}=await (getSupabaseClient().from('analysis_dimensions') as any).insert({owner_user_id:u,key:input.key.trim(),name:input.name.trim()}).select('*').single(); if(error) throw new Error(`Failed to save analysis dimension: ${error.message}`); return mapD(data)}
export async function updateDimension(id:string,input:{key:string;name:string}){const u=await req(); const {data,error}=await (getSupabaseClient().from('analysis_dimensions') as any).update({key:input.key.trim(),name:input.name.trim()}).eq('id',id).eq('owner_user_id',u).select('*').single(); if(error) throw new Error(`Failed to save analysis dimension: ${error.message}`); return mapD(data)}
export async function deleteDimension(id:string){const u=await req(); const {error}=await getSupabaseClient().from('analysis_dimensions').delete().eq('id',id).eq('owner_user_id',u); if(error) throw new Error(`Failed to delete analysis dimension: ${error.message}`)}
export async function listDimensionValues(dimensionId:string){const u=await req(); const {data,error}=await getSupabaseClient().from('analysis_dimension_values').select('*').eq('owner_user_id',u).eq('analysis_dimension_id',dimensionId).order('sort_order').order('name'); if(error) throw new Error(`Failed to load analysis dimensions: ${error.message}`); return (data??[]).map(mapV)}
export async function createDimensionValue(input:{analysisDimensionId:string;name:string;code?:string}){const u=await req(); const {data,error}=await (getSupabaseClient().from('analysis_dimension_values') as any).insert({owner_user_id:u,analysis_dimension_id:input.analysisDimensionId,name:input.name.trim(),code:input.code?.trim()||null}).select('*').single(); if(error) throw new Error(`Failed to save dimension value: ${error.message}`); return mapV(data)}
export async function updateDimensionValue(id:string,input:{name:string;code?:string}){const u=await req(); const {data,error}=await (getSupabaseClient().from('analysis_dimension_values') as any).update({name:input.name.trim(),code:input.code?.trim()||null}).eq('id',id).eq('owner_user_id',u).select('*').single(); if(error) throw new Error(`Failed to save dimension value: ${error.message}`); return mapV(data)}
export async function deleteDimensionValue(id:string){const u=await req(); const {error}=await getSupabaseClient().from('analysis_dimension_values').delete().eq('id',id).eq('owner_user_id',u); if(error) throw new Error(`Failed to save dimension value: ${error.message}`)}
